sonar.projectKey=Solierrr_api-recommendation
sonar.organization=solierrr

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
