sonar.projectKey=Solierrr_api-recommendation
sonar.organization=solierrr
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=.github/**,**/__pycache__/**
